version: '3.7'
services:
    server:
        build:
            dockerfile: Dockerfile
        environment:
            - TZ=Asia/Seoul
            - NODE_ENV=dev
            - DB_HOST=host.docker.internal
            - SERVER_PORT=3000
        container_name: nest-backend
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - redis
        extra_hosts:
            - 'host.docker.internal:host-gateway'